RequistionsMgt/RequistionsMgt/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('requistions.urls'))
]

RequistionsMgt/requistions/urls.py
from django.urls import path
from . import views
app_name='requistions'
urlpatterns=[

path('',views.index,name='index'),
path('requistions/',views.requisition_list,name='requistion_list'),
path('requistions/<int:pk>',views.get_requisition,name='requistion_get'),
path('add_requistion/',views.new_requistion,name='new_requistion'),
path('requistion_detail/<int:requistion_id>',views.add_details,name='add_details')

]

RequistionsMgt/requistions/models.py
from django.db import models
from django.db.models.signals import post_save, post_delete
from django.dispatch import receiver

# Create your models here.
class Station(models.Model):
    station_name=models.CharField(max_length=100,verbose_name='station')
    class Meta:
        verbose_name_plural='stations'
    def __str__ (self):
        return self.station_name
class Position(models.Model):
    position_name=models.CharField(max_length=100,verbose_name='position')
    class Meta:
        verbose_name_plural='positions'
    def __str__ (self):
        return self.position_name
class SalaryScale(models.Model):
    scale_name=models.CharField(max_length=100,verbose_name='salary scale name')
    class Meta:
        verbose_name_plural='salaryscales'
    def __str__ (self):
        return self.scale_name

class RequestType(models.Model):
    ## e.g NOA,SDA,Advance
    type_name=models.CharField(max_length=100, verbose_name='Requisition Type')
    class Meta:
        verbose_name_plural='requesttypes'
    def __str__ (self):
        return self.type_name
class RateType(models.Model):
    ## e.g travel abroad, travel inland
    type_name=models.CharField(max_length=100, verbose_name='Rate Type')
    class Meta:
        verbose_name_plural='ratetypes'
    def __str__ (self):
        return self.type_name
## Allowances rates ...depending on rate type and salary scales
class AllowanceRate(models.Model):    
    allowance_scale=models.ForeignKey(SalaryScale,on_delete=models.CASCADE)
    allowance_rate=models.ForeignKey(RateType,on_delete=models.CASCADE)
    amount=models.FloatField(default=0)
    class Meta:
        verbose_name_plural='Allowance rates'
    def __str__ (self):
        return self.allowance_rate

class Directorate(models.Model):
    directorate_name=models.CharField(max_length=100)
    class Meta:
        verbose_name_plural='Directorates'


    def __str__ (self):
        return self.directorate_name
    
class Period(models.Model):
    period_name=models.CharField(max_length=50,verbose_name='Period name')
    p_number=models.IntegerField(verbose_name='period number')
    startdate=models.DateField()
    enddate=models.DateField()
    num_days=models.IntegerField(default=30,verbose_name="Number of Days")
    p_flag=models.BooleanField(default=True)

    class Meta:
        verbose_name_plural='Periods'
    def __str__ (self):
        return self.period_name

class Employee(models.Model):
    emp_name=models.CharField(max_length=200,verbose_name='employee name')
    staff_id_num=models.CharField(max_length=20, unique=True, verbose_name='UNRAID No.')
    emp_station=models.ForeignKey(Station, on_delete=models.CASCADE)
    emp_position=models.ForeignKey(Position, on_delete=models.CASCADE)
    emp_scale=models.ForeignKey(SalaryScale, on_delete=models.CASCADE)
    date_left_org=models.DateField(null=True)
    class Meta:
        verbose_name_plural='Employees'
    def __str__ (self):
        return self.emp_name

class RequisitionDetailType(models.Model):
    ## e.g request for NOA,SDA,Advance,expense claim
    detail_name=models.CharField(max_length=100)
    objects = models.Manager()
    class Meta:
        verbose_name_plural='Requisition detail types'
    def __str__ (self):
        return self.detail_name
class Requisition(models.Model):
    made_by=models.ForeignKey(Employee, on_delete=models.CASCADE)
    date_made=models.DateTimeField(auto_now_add=True)
    purpose=models.TextField(verbose_name='Purpose')
    total =models.DecimalField(max_digits=10, decimal_places=2, default=0.0)
    class Meta:
        verbose_name_plural='Requisition'
    def __str__ (self):
        return self.purpose
class RequisitionDetail(models.Model):
    requisition = models.ForeignKey(Requisition, null=True, on_delete=models.CASCADE)
    emp_name = models.ForeignKey(Employee, on_delete=models.CASCADE)
    detail_type = models.ForeignKey(RequisitionDetailType, on_delete=models.CASCADE)
    period_claimed = models.ForeignKey(Period, on_delete=models.CASCADE)
    ndays = models.IntegerField(default=0, verbose_name="Number of days")
    startdate = models.DateField(null=True)
    enddate = models.DateField(null=True)
    rate = models.DecimalField(max_digits=10, decimal_places=2, default=0.0, verbose_name='Allowances Rate')
    amount = models.DecimalField(max_digits=10, decimal_places=2, default=0.0, verbose_name='Amount')
    class Meta:
        verbose_name_plural='Requisition details'
        
@receiver(post_save, sender=RequisitionDetail)
def add_requisition_total(sender, instance, **kwargs):
    requisition = instance.requisition
    requisition.total = requisition.total + instance.amount
    requisition.save()

@receiver(post_delete, sender=RequisitionDetail)
def substract_requisition_total(sender, instance, **kwargs):
    requisition = instance.requisition
    requisition.total = requisition.total - instance.amount
    requisition.save()
class RequisitionTotal(models.Model) :
    date_made=models.DateField(db_column='date_made')
    purpose=models.CharField(max_length=400, db_column='purpose')
    made_by=models.ForeignKey(Employee, on_delete=models.DO_NOTHING)
    total=models.FloatField(db_column='Total')   
    
    def __str__ (self):
        return self.purpose
    class Meta:
        verbose_name_plural='Requisition totals'

RequistionsMgt/requistions/forms.py
from django import forms
from .models import Requisition,RequisitionDetail
class RequisitionForm(forms.ModelForm):
    class Meta:
        model=Requisition
        fields = [
            'made_by',
            'purpose'
        ]


class RequisitionDetailForm(forms.ModelForm):
    class Meta:
        model = RequisitionDetail
        fields = [
            'emp_name',
            'detail_type',
            'period_claimed',
            'ndays',
            'startdate',
            'enddate',
            'rate',
            'amount'
        ]

RequistionsMgt/requistions/views.py
from django.shortcuts import render,redirect, get_object_or_404
from .models import Requisition,RequisitionTotal
from  django.db.models import Sum
from .forms import RequisitionForm, RequisitionDetailForm

# Create your views here.
def index (request):
    return render(request,'requistions/index.html')

def requisition_list(request):
    requisitions = Requisition.objects.all().order_by('date_made') 
    return render(request,'requistions/requistions.html', {
        "requisitions": requisitions
    })


def get_requisition(request,pk):
    requisition = Requisition.objects.get(id=pk)
    req_details = requisition.requisitiondetail_set.order_by('id')
    context={
        'requisition': requisition, 
        'details':req_details
    }
    return render(request,'requistions/requistion.html',context)

def new_requistion(request):
    if request.method !='POST':
        # if no data submitted ,create a blank form
        form=RequisitionForm()
    else:
        # post data submitted
        form=RequistionForm(data=request.POST)  
        if form.is_valid():
            form.save()  
            return  redirect('requistions:requistion_list')
        
    #display a blank or invalid form
    context={'form': form}
    return render(request,'requistions/requistion_add.html',context)

    
def add_details(request, requistion_id):
    requisition =  Requisition.objects.get(pk=requistion_id)
    form = RequisitionDetailForm(request.POST or None)
    if form.is_valid():
        detail = form.save(commit=False)
        detail.requisition = requisition
        detail.save()        
        return  redirect('requistions:requistion_get', pk=requisition.id)
    context = {
        'requistion':requisition,
        'form': form
    }
    return render(request,'requistions/requistion_detail_add.html',context)

RequistionsMgt/templates/requistions/base.html
<!DOCTYPE html>
<html>
<head>
 <title>UNRA Online Requistions MGT</title>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.21/css/jquery.dataTables.min.css"/>
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/autofill/2.3.5/css/autoFill.dataTables.css"/>
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/buttons/1.6.2/css/buttons.dataTables.min.css"/>
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/colreorder/1.5.2/css/colReorder.dataTables.min.css"/>
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/fixedheader/3.1.7/css/fixedHeader.dataTables.min.css"/>
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/responsive/2.2.4/css/responsive.dataTables.min.css"/>
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/searchpanes/1.1.0/css/searchPanes.dataTables.min.css"/>


 <script   src="https://code.jquery.com/jquery-3.5.1.slim.js"  integrity="sha256-DrT5NfxfbHvMHux31Lkhxg42LY6of8TaYyK50jnxRnM="  crossorigin="anonymous">
</script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>


<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jszip/2.5.0/jszip.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/pdfmake.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/vfs_fonts.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/1.10.21/js/jquery.dataTables.min.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/autofill/2.3.5/js/dataTables.autoFill.min.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/buttons/1.6.2/js/dataTables.buttons.min.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/buttons/1.6.2/js/buttons.html5.min.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/buttons/1.6.2/js/buttons.print.min.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/colreorder/1.5.2/js/dataTables.colReorder.min.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/fixedheader/3.1.7/js/dataTables.fixedHeader.min.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/responsive/2.2.4/js/dataTables.responsive.min.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/searchpanes/1.1.0/js/dataTables.searchPanes.min.js"></script>


 <script type="text/javascript">
	 $(document).ready(function() {
     $('#details-table').DataTable(
	  {
        dom: 'Bfrtip',
        buttons: [
            'copy', 'csv', 'excel', 'pdf', 'print'
        ]
	 
	 }
	 );
 } );
 </script>
 
 
</head>


<body>

<div class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

            </div>
            <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
						<li><a href="{% url 'requistions:index'%}"> Home </a></li>                        
						<li><a href="{% url 'requistions:requistion_list'%}"> Submitted Requistions  </a></li>
                </ul>
            </div>
        </div>
    </div>



 <div class="container">
{% block content %}
{% endblock %}
</div>



{% block javascript %}
    {% endblock %}

</body>
</html>

RequistionsMgt/templates/requistions/details_partial_list.html
{% for t in details %}
  <tr>
    <td>{{ t.emp_name }}</td>  
    <td>{{ t.detail_type }}</td>
    <td>{{ t.period_claimed }}</td>
    <td>{{ t.ndays }}</td>
    <td>{{ t.startdate }}</td>
    <td>{{ t.enddate }}</td>  
    <td>{{ t.rate }}</td>    > 
    <td>{{ t.amount }}</td>
	<td style="width: 150px">
      <button type="button"
              class="btn btn-warning btn-sm js-update-tenancy"
              data-url="#">
        <span class="glyphicon glyphicon-pencil"></span> Edit
      </button>
	  </td>
	  
	  <td>
      <button type="button"
              class="btn btn-danger btn-sm js-delete-tenancy"
              data-url="#">
        <span class="glyphicon glyphicon-trash"></span> Delete
      </button>
    </td>
     
  </tr>
{% empty %}

  <tr>
    <td colspan="8" class="text-center bg-warning">No Tenant</td>
  </tr>
{% endfor %}

RequistionsMgt/templates/requistions/error.html
{% extends 'requistions/base.html'%}
{% block content %}
<p>
An error has happed . Contact the system admin

</p>

{% endblock content %}

RequistionsMgt/templates/requistions/index.html
{% extends 'requistions/base.html'%}
{% block content %}
<p>
E-Requistion Management helps you to submit your requistions remotely and attach all required supporting documents.
Submitting memos has never been so easier!

</p>

{% endblock content %}

RequistionsMgt/templates/requistions/requistion.html
{% extends 'requistions/base.html'%}
{% block content %}

<p>Requistion purpose: {{requistion}}</p>
<p> Requistion Details
</p>
<table class="table table-bordered " id="details-table">
    <thead>
     <tr>			
     <th>Employee Name</th>	  
     <th>Requistion Type</th>			
     <th>Period </th>	
     <th>Number of days </th>	
     <th>Start Date</th>
     <th>End date</th>
     <th>Allowance Rate </th>
     <th>Amount </th>     
     <th> Edit Line </th>	
     <th> Delete line </th>			
     </tr>
 
 </thead>
<tbody>
{% include 'requistions/details_partial_list.html' %}
</tbody>

</table>


{% endblock content %}

RequistionsMgt/templates/requistions/requistion_add.html
{% extends 'requistions/base.html'%}
{% block content %}
<p> Add New Requistion</p>
<form action="{% url 'requistions:new_requistion'  %}" method="POST">
    {% csrf_token %}
    {{ form.as_p}}
    <button name="submit"> Add Requistion</button>

</form>

{% endblock content %}

RequistionsMgt/templates/requistions/requistion_detail_add.html
{% extends 'requistions/base.html'%}
{% block content %}
<p>
    <a href="{% url 'requistions:requistion_get' requistion.pk %}"> {{requistion.purpose}}</a>
</p>

<p> Add Requistion Details </p>
<form action="{% url 'requistions:add_details' requistion.pk %}" method="POST">
    {% csrf_token %}
    {{ form.as_p}}
    <button name="submit"> Add Line </button>

</form>

{% endblock content %}

RequistionsMgt/templates/requistions/requistions.html
{% extends 'requistions/base.html'%}
{% block content %}
<a href="{% url 'requistions:new_requistion'  %}"> Add new Requistion </a>
<p>Your requistions submitted</p>
<table class="table table-bordered " id="submitted-table">
  <thead>
   <tr>			
   <th>Submitted by </th>	  
   <th>Date Submitted </th>			
   <th>Purpose </th>	
   <th>Total </th>
   <th> Add Details </th>
   <th> View Details </th>	
   <th> Delete line </th>	 		
   </tr>

</thead>
<tbody>
{% include 'requistions/requistions_partial_list.html' %}
</tbody>

{% endblock content %}

RequistionsMgt/templates/requistions/requistions_partial_list.html
{% for t in requisitions %}
  <tr>
    <td>{{ t.made_by }}</td>  
    <td>{{ t.date_made }}</td>
    <td>{{ t.purpose }}</td> 
    <td>{{ t.total }}</td>
    <td >
      <a href="{% url 'requistions:add_details' t.pk %}"> Add details</a>
      </td>

	<td >
    <a href="{% url 'requistions:requistion_get' t.pk %}"> View details</a>
	  </td>
	  
	  <td>
      <button type="button"
              class="btn btn-danger btn-sm js-delete-tenancy"
              data-url="#">
        <span class="glyphicon glyphicon-trash"></span> Delete
      </button>
    </td>
     
  </tr>
{% empty %}

  <tr>
    <td colspan="8" class="text-center bg-warning">No Requistions to display</td>
  </tr>
{% endfor %}